# Generated by Django 4.1.5 on 2023-01-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_id", models.CharField(blank=True, max_length=15, null=True)),
                ("title", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.CharField(blank=True, max_length=10, null=True)),
                ("story", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "detail",
                "managed": False,
            },
        ),
    ]
