# Generated by Django 4.1 on 2023-02-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('artist', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('story', models.TextField(blank=True, default='', null=True)),
                ('url', models.TextField(blank=True, default='', null=True)),
                ('path_thumb', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='recommendationapp.genre')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publish', to='recommendationapp.publisher')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
