# Generated by Django 4.1.6 on 2023-02-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendationapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rel_ar_aw",
            options={"ordering": ["r_artist__name", "r_artwork__title", "type"]},
        ),
        migrations.AlterModelOptions(
            name="rel_gr_aw",
            options={"ordering": ["r_artwork__title"]},
        ),
    ]
