# Generated by Django 4.1.6 on 2023-02-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendationapp", "0002_genre_publisher_artwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="uid",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
