# Generated by Django 4.1.7 on 2023-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommendationapp",
            "0003_member_userprofile_viewing_record_searching_record_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
