# Generated by Django 4.1.6 on 2023-02-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendationapp", "0003_alter_artwork_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="star",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="uid",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
