# Generated by Django 4.1.6 on 2023-02-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recommendationapp", "0003_password_user_userprofile_viewing_record_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "uid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="passwrod",
        ),
        migrations.RemoveField(
            model_name="user",
            name="userprofile",
        ),
        migrations.DeleteModel(
            name="Password",
        ),
        migrations.AlterField(
            model_name="luv_user_ar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="luv_user_artwork",
                to="recommendationapp.member",
            ),
        ),
        migrations.AlterField(
            model_name="searching_record",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_searching",
                to="recommendationapp.member",
            ),
        ),
        migrations.AlterField(
            model_name="viewing_record",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vw_user_artwork",
                to="recommendationapp.member",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
