# Generated by Django 4.1.7 on 2023-02-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recommendationapp", "0004_member_is_staff_member_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="member",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
