# Generated by Django 4.1.6 on 2023-02-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendationapp", "0004_artwork_star_alter_artwork_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="star",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
