# Generated by Django 4.1.6 on 2023-02-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recommendationapp", "0005_alter_artwork_star"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rel_gr_aw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "r_artwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aw_gr",
                        to="recommendationapp.artwork",
                    ),
                ),
                (
                    "r_genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gr_aw",
                        to="recommendationapp.genre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rel_ar_aw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "r_artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_aw",
                        to="recommendationapp.artist",
                    ),
                ),
                (
                    "r_artwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aw_ar",
                        to="recommendationapp.artwork",
                    ),
                ),
            ],
        ),
    ]
